[package_fields]
spec_file = "hello-world-java.sss"
package_name = "hello-world-java"
version_number = "1.0.0"
revision_number = "1"
homepage = "https://github.com/eth-pkg/pkg-builder#examples"

[package_type]
# virtual | git | default
package_type="default"
tarball_url = "hello-world-java-1.0.0.tar.gz"
tarball_hash = "c361ad7853f4eb1e272eb10fe70ac8a5fd40677da5d23e205e1808f2c6f3bed7"

[package_type.language_env]
language_env = "java"
is_oracle=true
jdk_version="17.0"
jdk_binary_url="https://download.oracle.com/java/17/archive/jdk-17.0.10_linux-x64_bin.tar.gz"
jdk_binary_checksum="e4fb2df9a32a876afb0a6e17f54c594c2780e18badfa2e8fc99bc2656b0a57b1"

[build_env]
codename="jammy jellyfish"
arch = "amd64"
pkg_builder_version="0.2.1"
debcrafter_version = "2711b53"
run_lintian=true
run_piuparts=true
run_autopkgtest=true
lintian_version="2.116.3"
piuparts_version="1.1.7"
autopkgtest_version="5.20"
sbuild_version="0.85.6"
# package directory
workdir = "~/.pkg-builder/packages"